### ISSUE TITLE
Support for default values

### ISSUE THREAD

**Issue by ReneSac** [fenekku/commandeer#1]
One should be able to provide default values for options.

**Comment by fenekku** [comment]
:+1: Absolutely. Thanks for using the issues - it's probably more efficient than me just writing these things down on the README :sweat_smile: . I want to get a good testing framework setup first. Any ideas on that are welcome.

**Comment by ReneSac** [comment]
Yeah, it is more organized, and with a forum attached. No ideas on the testing framework though.

**Comment by fenekku** [comment]
Finally done!
