### ISSUE TITLE
Aliases for subcommands

### ISSUE THREAD

**Issue by moigagoo** [fenekku/commandeer#11]
I would be great to be able to define a subcommand like so:

``` nim
commandline:
  subcommand build, ["build", "make"]:
    option projectPath, string, "path", "p", "."
    option targetFormat, string, "target", "t"
    exitoption "help", "h", buildUsage
```

I.e. provide multiple names pointing to the same subcommand.

**Comment by fenekku** [comment]
Will fix circleci setup in a couple of days. I am keeping this open until then.

**Comment by fenekku** [comment]
It comes full circle (yeah, I am not ashamed of this pun!): Circleci is fixed thanks to your docker image @moigagoo. @pandanautinspace 's contribution has been merged in and the new version has been tagged. You can now define a subcommand as so:

```nim
commandline:
  subcommand build, ["build", "make"]:
    option projectPath, string, "path", "p", "."
    option targetFormat, string, "target", "t"
    exitoption "help", "h", buildUsage
  subcommand serve, "serve", "server", "s":
    option testing, bool, "testing", "t"
```
