### ISSUE TITLE
Commandeer doesn't compile on 0.14.3 (devel branch) of compiler

### ISSUE THREAD

**Issue by singularperturbation** [fenekku/commandeer#12]
Getting `commandeer.nim(114, 8) Error: undeclared identifier: 'strtabs'` as error message when trying to compile on latest version of the compiler.

I'm not sure if it makes sense to leave the bind statements in the templates, since this is the [default behavior](http://nim-lang.org/docs/manual.html#generics-bind-statement) for symbol binding anyway.

**Comment by fenekku** [comment]
Fixed by pull request #14
